### PR TITLE
Clean up and rebuild for OpenMM 8

### PR DESCRIPTION
**Pull request by raimis**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Please add any other relevant info below:
- [x] Clean the Linux build script
- [x] Fix the linking on Linux
- [x] Fix for SWIG >=4.1
- [x] Rebuild for OpenMM 8

### CODE REVIEW

**Comment by raimis** [comment]
@conda-forge-admin, please rerender

**Comment by raimis** [comment]
@conda-forge-admin, please rerender

**Comment by raimis** [comment]
@egallicc could you review?

**Comment by egallicc** [comment]
Thank you for the excellent contribution @raimis

**Pull request merged**
